### ISSUE TITLE
[Help] Using Icons

### ISSUE THREAD

**Issue by mentosweet** [Ellpeck/ObsidianCustomFrames#100]
Hi, I am unsure of how to customise the icons. Do i need to code it or something?

Thanks in advance! 

![Screenshot 2023-09-09 170731](https://github.com/Ellpeck/ObsidianCustomFrames/assets/137807059/8adbe6a9-59ef-4a32-af68-109e4497f07d)

**Comment by Ellpeck** [comment]
Hi! You have to input the name of the icon you want to use. You can find a list of the icons and their names on the Lucide website, which is linked in the screenshot you showed. Good luck!
