### ISSUE TITLE
lucide icon "book-user" doesn't work, but "book" does.

### ISSUE THREAD

**Issue by simonvanbernem** [Ellpeck/ObsidianCustomFrames#108]
When trying to use the [book-user icon from Lucide](https://lucide.dev/icons/book-user), no icon appears at all:
![grafik](https://github.com/Ellpeck/ObsidianCustomFrames/assets/10748498/66478134-6bfc-4039-af06-e6060c5fcf15)

![grafik](https://github.com/Ellpeck/ObsidianCustomFrames/assets/10748498/a39e13ad-9bca-43ee-9f9a-df70c61f6719)

Trying the same with the [book icon](https://lucide.dev/icons/book) works correctly:
![grafik](https://github.com/Ellpeck/ObsidianCustomFrames/assets/10748498/982643a0-af14-41b6-9c65-dbf16fa1c9e7)

So there seems to be some issue with getting the book-user icon. Maybe the code doesn't handle the dash in the name correctly?

**Comment by Ellpeck** [comment]
This plugin just uses Obsidian's built-in ability to use Lucide icons for tab icons. I assume this issue is due to the fact that Obsidian ships with an outdated version of Lucide icons. Other than that, see #71 for a feature request to add the ability to specify different types of icons.
