### ISSUE TITLE
Using GPT4 will require entering a verification code

### ISSUE THREAD

**Issue by 2445868686** [Ellpeck/ObsidianCustomFrames#109]
I implanted chatopenai.com into the observer using a custom frame. When using GPT4, I am required to enter a verification code every time, but GPT3.5 does not know how to solve this small problem

**Comment by Ellpeck** [comment]
Hi, can you elaborate on this issue please? What is the expected behavior from this website outside of Custom Frames, and what is different about it in Custom Frames?

**Comment by 2445868686** [comment]
> Hi, can you elaborate on this issue please? What is the expected behavior from this website outside of Custom Frames, and what is different about it in Custom Frames?嗨，你能详细说明这个问题吗？在自定义框架之外，本网站的预期行为是什么，在自定义框架中有什么不同？

Since identifying this issue, I have been unable to replicate it, which suggests that the problem may be related to my network's performance.

**Comment by Ellpeck** [comment]
Okay! Let me know if it happens again and I can reopen this issue :)

**Comment by 2445868686** [comment]
> Okay! Let me know if it happens again and I can reopen this issue :)

thank you very much
