### ISSUE TITLE
Copy button in Newbing answer doesn't work

### ISSUE THREAD

**Issue by wwjCMP** [Ellpeck/ObsidianCustomFrames#110]
https://www.bing.com/search?q=Bing+AI&showconv=1&ntref=1

![image](https://github.com/Ellpeck/ObsidianCustomFrames/assets/32979859/8ca14d84-c24a-428d-b66d-0ed51e1cae70)

**Comment by Ellpeck** [comment]
Duplicate of #98

**Comment by nevertoday** [comment]
very sad
