### ISSUE TITLE
Your browser is blocking the clipboard, please check your browser permissions, try a different browser or click Download.

### ISSUE THREAD

**Issue by bsszds** [Ellpeck/ObsidianCustomFrames#111]
After embedding this URL and registering to log in, the copy link appears unable to be retrieved from the clipboard

 {"url": "https://www.streamlinehq.com/freebies",
      "displayName": "Freebies"
}

![image](https://github.com/Ellpeck/ObsidianCustomFrames/assets/52306372/98eeb0cc-098f-4d5d-8de7-972bbd363128)

**Comment by bsszds** [comment]
obsidian V1.5.3

**Comment by Ellpeck** [comment]
Duplicate of #98
