### ISSUE TITLE
Is there a way to make YouTube transcripts draggable

### ISSUE THREAD

**Issue by bfcs** [Ellpeck/ObsidianCustomFrames#112]
It would be useful for taking video note
<img width="575" alt="image" src="https://github.com/Ellpeck/ObsidianCustomFrames/assets/52602045/9567beba-56e7-4b8c-890b-3e69733fac67">

**Comment by Ellpeck** [comment]
Hi, I'm not sure what you mean unfortunately. Is this a feature that the regular YouTube site supports?
