### ISSUE TITLE
YouTube Code Block

### ISSUE THREAD

**Issue by CraigRGordon** [Ellpeck/ObsidianCustomFrames#115]
Instead of adding in a bunch of frames for every video I want to write up something on is there a way to manually create a custom-frame with just the code block?
```powershell

#   ``````custom-frame
All properties listed here and values
#    ``````

```

**Comment by Ellpeck** [comment]
Hi! You can just create a single custom frame that links to YouTube itself, and then use the `urlSuffix` property to link the video you want to link. Specifically, you can set something like this:

The frame's url as `https://www.youtube.com/watch?v=`

And then a video can be displayed as 

```custom-frame
frame: YouTube Video
urlSuffix: <video id>
```
