### ISSUE TITLE
How to make TiTick match my theme?

### ISSUE THREAD

**Issue by rk-kontur** [Ellpeck/ObsidianCustomFrames#116]
Hi there and THANKS for ths great plugin. It works very well with TickTick.

There is only one issue: TickTick offers a limited amount of themes (mainly black and white)

Is there any way to CSS style / override this so the TickTick frame matches my theme?

Apart from that: ROCK ON!
This is GREAT!!!

**Comment by Ellpeck** [comment]
Hi! You can us the "Custom Css" box for the frame to style the frame any way you like :)
