### ISSUE TITLE
I can't use Copy button.

### ISSUE THREAD

**Issue by choies1** [Ellpeck/ObsidianCustomFrames#121]
I use Caude 3 using customframes.

I can use other buttons. But I can't use Copy button.

Please check it.

![image](https://github.com/Ellpeck/ObsidianCustomFrames/assets/10408785/0f18bd25-3888-4c4f-9e55-6a9c1dfebc38)

**Comment by Ellpeck** [comment]
This is a duplicate of #98

**Comment by nevertoday** [comment]
+1
