### ISSUE TITLE
Possibility to add other plugins sidebars

### ISSUE THREAD

**Issue by feedhopper** [Ellpeck/ObsidianCustomFrames#124]
It would be great to have a chance to "compile" other plugin panels into one. For instance: having quiet outline and pomodoro underneath each other without having to divide the side panel in two.

This would essentially allow Obsidian to create layouts such as the ones used in Premiere with tabs in sidebar that can be individually configured

**Comment by Ellpeck** [comment]
Hi! This seems out of scope of this plugin, as its point is to allow displaying web pages in Obsidian views. Sorry!
