### ISSUE TITLE
Is it possible to hide the address bar for center frames?

### ISSUE THREAD

**Issue by rafaelliu** [Ellpeck/ObsidianCustomFrames#125]
Panel frames already have the address bar hidden, but if I move it to the center the bar appears. For many sites, the go back/fwd, refresh, etc are not very helpful. It would be great to be able to disable/hide that bar

**Comment by Ellpeck** [comment]
Hi! What you call the address bar is just the default Obsidian top bar that every center tab has. I don't think there's a way to disable it per specific tab content, I think it's only possible to disable it globally through the "Show tab title bar" setting.
