### ISSUE TITLE
[Feature Request] Add "force mobile view" for custom frames

### ISSUE THREAD

**Issue by Obadiahcruz** [Ellpeck/ObsidianCustomFrames#14]
It would be nice to have a force frame to mobile dimensions for our custom frames. this would avoid us to have to put in the mobile url of the websites. Some websites dont have simple mobile urls

**Comment by Obadiahcruz** [comment]
hi @Ellpeck ! i think at the time i was asking for a way to have the plugin to force a mobile view for all urls. some websites dont have simple mobile urls and you have to personally know them or look for them. 

so yes the chromium dev tools to emulate a mobile device for the urls 

this would help the side panels to be used for custom iframes

**Comment by Ellpeck** [comment]
This can be combined into one feature using #26
