### ISSUE TITLE
Need to re-log in when using Todoist

### ISSUE THREAD

**Issue by Parzival503** [Ellpeck/ObsidianCustomFrames#16]
I am prompted to re log-in every time I close the custom frame and re-open it. (Parzival#2350)

**Comment by RemyBoulben** [comment]
I though I had a similar problem as I had to click on 'My Todoist' every time to see the app, changed the url for the pane (in settings) to "https://todoist.com/app/today" fixed it.

**Comment by Ellpeck** [comment]
Hi @Parzival503, can you try to figure out if the solution proposed by @RemyBoulben works for you, as well? If so, I will change the Todoist preset's default URL to the one suggested.

**Comment by Ellpeck** [comment]
Hi! I'm closing this issue for now due to inactivity. If you're still experiencing it, please leave a comment so I can reopen it.
