### ISSUE TITLE
Custom Frame does not like being beside another Custom Frame when placed on the Sidebars

### ISSUE THREAD

**Issue by ceciliamay** [Ellpeck/ObsidianCustomFrames#19]
Hey there @Ellpeck !! This plugin is making me smile everytime I use it. I can't thank you enough for this!! Onto the issue...

Problem:
Custom Frame does not like being beside another Custom Frame when placed on the Sidebars

How to Replicate:
Add a custom frame and put it to the left sidebar. Add another custom frame and drag it over to left sidebar to be beside the first custom frame.

Expected Behavior:
The new custom frame sits beside the first custom frame.

Current Behavior:
It is very hard to "aim" for the new custom frame to sit beside the other custom frame. It only wants to be on the top or bottom.

I am trying to use my left sidebar as my go to search area/other tools hotspot with all the custom frames I added. Unfortunately, I can't put them all in line due to this bug.

**Comment by Ellpeck** [comment]
Hi! Does this problem get less bad/go away if you increase the padding in the settings menu? It's the first option right at the top. 

It seems like this issue generally happens when you try to move anything around over the actual embed, as that makes the mouse go wonky. Increasing the padding should give you a bigger area that allows for anchoring the panes like you want.

Unfortunately, I've yet to find a way to fix this permanently (and to allow dragging over the embed without any trouble), and it seems like it might be an Obsidian issue, and not a plugin issue.

**Comment by ceciliamay** [comment]
Ha!! I forgot about the padding. (mainly cause I set it at 0 when I saw it 😂) It works!! Thanks for this!!

### Workaround:
1. Increase padding up to 15px for Custom Frames
1. Setup all custom frames and open them
1. Drag the custom frames, and when adding a new one beside it, drag it to the left/right padding
1. Drop
1. Save Workspace setup
1. [optional] Go back to Custom Frames and set padding to 0 (if you still want the 0px padding)
1. Reload
1. Yaaay!! 

![image](https://user-images.githubusercontent.com/90643719/161881572-6aba609f-6e55-4b8b-98a7-41cb72b5d417.png)

Thank you @Ellpeck for looking into this!!

**Comment by marcjulianschwarz** [comment]
I don't know if this is the same problem or not. I am having issues resizing the frames (panes with frame inside). Making it wider is working perfectly however it starts behaving a bit weird when trying to make it narrower. 

Where would I need to put the padding on? The body of a frame?

Attached a video showing the issue.

https://user-images.githubusercontent.com/67844154/162815799-86735b76-5e6a-41f5-a899-f39906db32e9.mp4

**Comment by marcjulianschwarz** [comment]
Well, just got it fixed.

For anyone reading this:
You can add 15-20px of padding on `.custom-frames-frame` and move the mouse slowly to prevent entering the iframe.

**Comment by Ellpeck** [comment]
This issue has been fixed in the most recent Insiders release of Obsidian (0.14.6).
