### ISSUE TITLE
[Question] Google Drive in dark theme cannot be read

### ISSUE THREAD

**Issue by emisjerry** [Ellpeck/ObsidianCustomFrames#2]
I'm not sure it's the problem of Google Drive or plugin? When Obsidian in dark theme, the Google Drive page text color is black, which cannot be seen.

![image](https://user-images.githubusercontent.com/131511/159618270-9de3b089-6bd2-46b9-8cd0-0e0d7f732839.png)

**Comment by Ellpeck** [comment]
This is likely due to the Google Drive website not setting an explicit background color. To get around this issue for now, you can use the "Custom CSS" field in the settings to set a background color manually.
