### ISSUE TITLE
[Feature Request] Add search box for URLs

### ISSUE THREAD

**Issue by dubbyvee** [Ellpeck/ObsidianCustomFrames#22]
It would be nice to to have a search box in the right pane too so that we don't have to customize a preset if we're just on the go.

**Comment by Ellpeck** [comment]
Hi, thanks for the suggestion! This isn't really what Custom Frames is meant to be used for. If you're looking for a plugin that allows you to access any website quickly, I recommend [Search on Internet](https://github.com/HEmile/obsidian-search-on-internet) for that.
