### ISSUE TITLE
Clicking link in Google Keep causes Obsidian to crash.

### ISSUE THREAD

**Issue by stoweboyd** [Ellpeck/ObsidianCustomFrames#23]
I tried it twice. Kaboom both times.

**Comment by Ellpeck** [comment]
Hmm, I use Google Keep with Obsidian daily and clicking links has never caused any issues for me. What versions of Obsidian and the plugin are you on?

**Comment by stoweboyd** [comment]
Obsidian 0.14.5
custom frames 2.2.0

**Comment by Ellpeck** [comment]
Can you try with the most recent release of Custom Frames (2.2.2)? Thanks!

**Comment by Ellpeck** [comment]
See #25 since it is almost certainly related, please try to test with the debug version posted there as well, if you can. Closing this for now, as the webview/iframe toggle will be added in the next release, which should also resolve this issue.
