### ISSUE TITLE
Not able to log on on Google when trying to use Google Keep

### ISSUE THREAD

**Issue by ccjcan** [Ellpeck/ObsidianCustomFrames#24]
Hi nice idea and plugin, tested today, it adds the plugin to the sidebar (as keep), but when I try to log-on using Google (inside frame) it goes back to the logon (Google Screen).

**Comment by Ellpeck** [comment]
What versions of the plugin and Obsidian are you on?

**Comment by ccjcan** [comment]
Plugin 2.1.0
Obsidian 0.14.5

**Comment by Ellpeck** [comment]
Please update to the most recent version of the plugin.

**Comment by ccjcan** [comment]
Updated, I was able to logon but it doesn't hide the top frame like yours.
this is what I see.
[image: image.png]

**Comment by Ellpeck** [comment]
Did you restart or reload Obsidian before trying to open the Google Drive frame?

Also, the element hiding only works consistently for the first page navigated to, which is a limitation of the CSS injection. It should work now that you're logged in.

**Comment by ccjcan** [comment]
> 

Updates: Google Drive frame worked after I restarted Obsidian.
The Google Keep CSS injection didn't work even after logging in and restarting Obsidian.

**Comment by Ellpeck** [comment]
What CSS injection are you using? Is it the one from 2.2.1 and later, or an earlier version?

**Comment by ccjcan** [comment]
CSS seems to do the trick with Keep this time (your latest update), however, the plugin is creating a strange behavior when I try to resize the side bar (make it smaller), it keeps pushing the the left ...

**Comment by Ellpeck** [comment]
That is an issue with Obsidian 0.14.5 and older. This issue is fixed in Obsidian 0.14.6, which is currently in Insider.
