### ISSUE TITLE
[Question] Cannot login to GitHub

### ISSUE THREAD

**Issue by emisjerry** [Ellpeck/ObsidianCustomFrames#3]
I'm using github for testing, in the frame pane, i cannot signin to my GitHub. It responed the following message:

```
Cookies must be enabled to use GitHub.
```

**Comment by Ellpeck** [comment]
Hmm, it doesn't look like I can do anything about this from my end without overriding @lishid's new header policies in Obsidian. Stay tuned though, we might be able to figure something out!

**Comment by Ellpeck** [comment]
This issue will be fixed in the next preview version of Obsidian thanks to @lishid! Until then, you'll have to access GitHub manually, unfortunately.
