### ISSUE TITLE
Webapp fails to load JS libraries

### ISSUE THREAD

**Issue by janschlatter** [Ellpeck/ObsidianCustomFrames#31]
Hi,

When I'm trying to access https://app.mochi.cards with this plugin, the console throws these errors:

![grafik](https://user-images.githubusercontent.com/63644885/167249672-707bf517-05e8-4788-bb0e-273049ccd942.png)

This is the specific line in the js:

![grafik](https://user-images.githubusercontent.com/63644885/167249655-f319dfed-b208-4d09-854e-61e6299fb1d1.png)

I tried the not-electron iframe option but that throws other errors:

![grafik](https://user-images.githubusercontent.com/63644885/167249826-f31dfad7-c86d-4f53-bf43-078a3c096e09.png)

Any ideas on if it's fixable? Or a limitation / bug from the website's end? Thanks so much!

**Comment by Ellpeck** [comment]
Obsidian's iframes and webviews don't allow cross-site requests or loading Node dependencies from third-party sites. This is a security restriction, as anything else would allow malicious sites to access information from within your Obsidian vault if you access them from within Obsidian. Sorry!

**Comment by janschlatter** [comment]
That sounds very reasonable, haha. Thanks for the explanation and the quick reply!
