### ISSUE TITLE
Feature Request - Refresh frame button

### ISSUE THREAD

**Issue by pcause** [Ellpeck/ObsidianCustomFrames#35]
I'd like the ability to refresh the frame contents.  Perhaps in the spec of the frame you can include a "refreshbutton" item (above/below/no, default no) and then below/above the frame you have the button and when pressed can reload the frame contents.

**Comment by Ellpeck** [comment]
There's already a refresh button, as well as few other buttons for page navigation. If the frame is open in the center pane, the buttons will be lined up along the right side of the top of the pane. If the frame is open on one of the side panes, you can right-click the tab icon to access the additional controls.

**Comment by pcause** [comment]
> There's already a refresh button, as well as few other buttons for page navigation. If the frame is open in the center pane, the buttons will be lined up along the right side of the top of the pane. If the frame is open on one of the side panes, you can right-click the tab icon to access the additional controls.

I have a custom frame and there are no buttons anywhere for refresh.  Using latest insider build.  I built a page with just a frame  using the ```custom-frame  and some custom css in that, where I set height.  no buttons for refresh anywhere.

**Comment by Ellpeck** [comment]
Markdown mode doesn't support these features yet, since it's a very new addition. This is already on [the roadmap](https://github.com/Ellpeck/ObsidianCustomFrames#%EF%B8%8F-roadmap), though.

**Comment by pcause** [comment]
Not sure then what the comment about the refresh buttons means, but thanks.  Using the plugin, I really think the refresh capability is very important.

**Comment by Ellpeck** [comment]
Markdown mode is not the primary way that Custom Frames are intended to be used, it's just an additional feature that was added recently. Since you never explicitly mentioned that you're using Markdown mode, I assumed you were using the regular mode.
