### ISSUE TITLE
Google calendar custom frame modification request

### ISSUE THREAD

**Issue by Gourav1910** [Ellpeck/ObsidianCustomFrames#39]
Hi, I found the custom frame of google calendar is very helpful in the side panel for continuously tracking my time-blocked routine. 

![image](https://user-images.githubusercontent.com/101202140/174154047-437925c6-05b5-4d29-82ed-b81c5a3abe72.png)

But in the side panel, the upper header seems to be big. So is it possible for you to trim the upper header(where the date is written (FRI and 17 in blue circle)? It will be good for the visual experience.

**Comment by Gourav1910** [comment]
> Hi, I found the custom frame of google calendar is very helpful in the side panel for continuously tracking my time-blocked routine.
> 
> ![image](https://user-images.githubusercontent.com/101202140/174154047-437925c6-05b5-4d29-82ed-b81c5a3abe72.png)
> 
> But in the side panel, the upper header seems to be big. So is it possible for you to trim the upper header(where the date is written (FRI and 17 in blue circle)? It will be good for the visual experience.

**Comment by TekeTK** [comment]
think just add 

```
.JE11kf {
display: none !important;
}
```

to the css part

**Comment by Gourav1910** [comment]
You mean, I should add this in a css snippets or inside the custom frame setting of calendar?

**Comment by TekeTK** [comment]
That'll be the custom frame setting for the calendar in the plugin settings. Separate from your theme appearance CSS snippets.

**Comment by Gourav1910** [comment]
omg thanku thanku thanku😊😊🫡it worked. You made my day.

**Comment by Ellpeck** [comment]
Reopening this because I do want to include this in the default preset!

**Comment by Gourav1910** [comment]
> Reopening this because I do want to include this in the default preset!

I want to add one more issue from the custom frame of google keep.

![image](https://user-images.githubusercontent.com/101202140/175804007-380c56ae-7888-4fa6-b742-0d362423c0a4.png)

Why can't I able to open the main menu? Did you do this intentionally or did you forget about it?

**Comment by TekeTK** [comment]
I'll chime back in so you have something to work with. Replace the default custom frame CSS code in google keep with 
`div.PvRhvb.PvRhvb-qAWA2, 
div.gb_sc {
display: none;
}

div.PvRhvb-fozPsf-ysyhld {
min-width: 0px !important;
}`

Let me know if that returns menu functionality to your window. 

Also, as an extra, if you want to use google keep and tasks WITH your google calendar custom frame, you can remove the 'div.gboEAb,' and 'div.Kk7lMc-QWPxkf-LgbsSe-haAclf,' line (including the comma) which will return the right sidebar functionality so your code now looks like
`/* hide right-side menu, and some buttons */
div.d6McF,
div.pw6cBb,
div.gb_Td.gb_Va.gb_Id,
div.h8Aqhb,
div.dwlvNd,
.JE11kf {
    display: none !important;
}`

This include the previous fix mentioned. Let me know if that works for you.

**Comment by Ellpeck** [comment]
Unfortunately, neither one of these fixes can be used in the default plugin. As Google randomizes their CSS class names, any updates to the code (which happened a fair few times with Keep by now) will break most of the randomized names. This is why the default Keep preset uses the hierarchy of elements as a reference, rather than the class names.

If you want your fixes to be included in the plugin by default, you'll have to edit them to use as few class names as possible, unfortunately.

**Comment by TekeTK** [comment]
That's a bummer. I only just learned how to edit CSS this week so just now learning that. Makes sense though.

**Comment by TekeTK** [comment]
I think I found a solution. How about this?
_______________________________________
/* hide the menu bar and the "Keep" text */
html > body > div:nth-child(2) > div:nth-child(2) >  div:first-child[class*=" "], 
html > body > div:first-child > header:first-child > div > div:first-child > div > div:first-child, 
html > body > div:nth-child(2) > div:nth-child(2) >  div:first-child > div:first-child { 
	display: none !important; 
}
_______________________________________
The menu bar div class when folded (what we want to hide) is "PvRhvb PvRhvb-qAWA2" as opposed to menu when expanded "PvRhvb" so adding [class*=" "] can narrow perhaps?

The CSS doesn't display the child div if it contains a space (" ") despite the value changes with updates. Can also exclude the value containing a dash ("-")

Last added CSS was to just fix the spacing of other elements when opening and closing menu. Would this work instead?
