### ISSUE TITLE
logseq support

### ISSUE THREAD

**Issue by sigma2647** [Ellpeck/ObsidianCustomFrames#42]
![image](https://user-images.githubusercontent.com/61632637/176511456-e6ed4ba0-182b-48d2-b58c-5dc25236eb4a.png)
![image](https://user-images.githubusercontent.com/61632637/176511790-995cd09d-9f6e-4edd-88e3-d451e922e575.png)

when i open logseq on the web browser it ask me to grant filesystem premission , but in obsidian it doesn't show the prompt

**Comment by Ellpeck** [comment]
Hi, please open the dev tools in the custom frame using the top bar's "open dev tools" button (or right-clicking on the frame's icon if it's open in the sidebar) and share the console output you receive when loading or reloading the page (the latter of which can also be done in the same top menu). Thanks!

**Comment by sigma2647** [comment]
Hi Thank you for you support ,I tap the "open dev tools" button then refresh few times and it didn't show any info
![image](https://user-images.githubusercontent.com/61632637/176537013-e6ff2877-4da1-4a67-a43e-a4e0e4184e2d.png)

**Comment by sigma2647** [comment]
Thank you for your support , here's the info when loading the frame for logseq
![image](https://user-images.githubusercontent.com/61632637/176537475-536a9900-85d8-49cd-9da4-ae43d42aff5c.png)

**Comment by Ellpeck** [comment]
Hmm, unfortunately there might not be much we can do here, as file system access is limited in Obsidian's iframes and webviews due to security concerns related to node and the ability for websites to access your private files. 

You might just have to access this website externally, unfortunately.
