### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by zhl111** [Ellpeck/ObsidianCustomFrames#43]
Click on the link and obsidian crashes immediately
Airtable
![image](https://user-images.githubusercontent.com/29135984/178105014-d12af32d-d181-4cb4-b13a-2ff5a4e1c85b.png)

![image](https://user-images.githubusercontent.com/29135984/178104982-2610b194-520b-4309-9bdc-114156ce8120.png)

**Comment by Ellpeck** [comment]
This is possibly related to #46
