### ISSUE TITLE
Notion login fail

### ISSUE THREAD

**Issue by bryanwhiting** [Ellpeck/ObsidianCustomFrames#44]
Hi! I love custom frames for my google cal. It's been great to see. 

When I tried logging into Notion it brought up the SSO on the web, which I did. But then after choosing my google account it opens a url with a popup redirect and then doesn't seem to complete the authentication with the Obsidian web server. Any thoughts?

Thanks

**Comment by bryanwhiting** [comment]
Thanks for the help! I got it working!

I logged into Keep and Cal but neither worked. 

The problem was in Notion when I clicked the Google SSO button it would pop up Chrome for authentication, but then wouldn't complete with Obsidian. 

Instead I just typed my email into the "log in" section and Notion sent me a one time password. That worked like a charm.

**Comment by mariomarchi** [comment]
here I am in 2024 using this piece of information to solve my problem, thank you

> In #34, a user suggested logging in to the site you use for SSO (in your case, Google) from a different frame (like the Google Keep or Google Calendar preset ones), which might allow you to then log into Notion from your Notion frame (which shares the same cookies and local storage as other sites opened within Obsidian) without having to log into Google again.
