### ISSUE TITLE
Odd behaviour on Sliding Panes, Gmail Inbox

### ISSUE THREAD

**Issue by katanaglobal** [Ellpeck/ObsidianCustomFrames#45]
Odd behaviour on the plugin. 

I'm using sliding panes, obsidian 15.6, and I have a custom frame of gmail email inbox. 

When the plugin is on, I can't open new panes on click, and new panes do not stack as expected.

**Comment by Ellpeck** [comment]
Can you elaborate or maybe show screenshots/video recordings? I've never personally used the sliding panes plugin, so I'm not sure how to reproduce this issue!

**Comment by Ellpeck** [comment]
Hi! I'm closing this issue for now due to inactivity. If you're still experiencing it, please leave a comment so I can reopen it.
