### ISSUE TITLE
I can't log in Google Keep and Notion

### ISSUE THREAD

**Issue by Jack-KkKk** [Ellpeck/ObsidianCustomFrames#5]
Thanks for your decision! I can download your plugin and test it.

But It still has a problem. I tried to log in Google Keep, typed my Google ID and NEXT button, It showed same Login page and I couldn't log in Google Keep

I found this situation on Notion. 

Can you help me?

**Comment by Ellpeck** [comment]
Hi! As stated in the README, some sites like Google Keep have a heavy restriction on what can be displayed when using an iframe. This limitation will be mitigated almost entirely with Obsidian 0.14.3, which should be released shortly. Until then, you won't be able to use this plugin for certain sites, unfortunately.

**Comment by Jack-KkKk** [comment]
Thanks! I will wait Obsidian 0.14.3!

**Comment by Nedreow** [comment]
I had the same problem with trying to embed Google Sheets, thanks for the help.
