### ISSUE TITLE
What are the Style options within a markdown file?

### ISSUE THREAD

**Issue by newuser127** [Ellpeck/ObsidianCustomFrames#57]
Really enjoying your app. I just have a quick question. What are the style options when adding a website to a markdown file. I followed the following example below. However I would really like to adjust other features such as width and possibly colors. Can you list the available options? Also is it possible to have two websites in the side plane with one being below the other? Thanks

```custom-frames
frame: Google Keep
style: height: 1000px;
urlSuffix: #reminders
```

**Comment by Ellpeck** [comment]
Hi! The style options is just regular CSS, so anything you'd put in a CSS file works there too.

You can arrange custom frames in the sidebar as you would any other panes, so you can arrange two panes on top of each other by dragging one closer towards the bottom.

Good luck!
