### ISSUE TITLE
iFrame for Outlook Web App

### ISSUE THREAD

**Issue by kennygokh** [Ellpeck/ObsidianCustomFrames#64]
Hi, I have created a custom frame to open Outlook Web App. It works fine in a desktop. However, it loaded as a blank page on the iPad. Any idea what settings I have missed?

**Comment by Ellpeck** [comment]
Hi! Please see [this section](https://github.com/Ellpeck/ObsidianCustomFrames#-on-obsidian-mobile) for info on why this is happening.
