### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by Welding-Torch** [Ellpeck/ObsidianCustomFrames#7]
![image](https://user-images.githubusercontent.com/46340124/160247321-a5fef4cd-27f6-4a9c-84be-322c6dc22f71.png)

I installed the extension 10 minutes ago, signed into Google and I'm getting this error. I can go to the Google search engine and that's fully functional, but none of the webapps like docs/slides/google drive work. And when I try to go to Keep, I get this error. I tried both the button from the Google App drawer and a direct link by searching on Google.

Do let me know if any fix is possible, thanks

**Comment by Ellpeck** [comment]
Hi! As stated in the README:
> ⚠️⚠️⚠️ For header-heavy sites like Google Keep to work, this plugin requires Obsidian 0.14.3. ⚠️⚠️⚠️

You'll have to wait until that version is fully released. Sorry!

**Comment by Welding-Torch** [comment]
Ah I mistakenly assumed that was the latest public version, I'll wait for that to be released then

**Comment by Welding-Torch** [comment]
Update: It works now after the update, and it works BRILLIANTLY 🤩
