### ISSUE TITLE
[Feature Request] Override `prefers-color-scheme` for webview to match obsidian light/dark theme

### ISSUE THREAD

**Issue by replete** [Ellpeck/ObsidianCustomFrames#70]
I always have my OS set to dark theme, and the websites I use Custom Frames for (calendar) will load light or dark theme depending on the system setting (normally OS level) via the 'prefers-color-scheme' CSS feature.

It would be cool to override the webview's reported light/dark scheme based on whether Obsidian (our fake OS) is using a light or dark scheme.

I use the Minimal Theme and switch between light/dark throughout the day quite often depending on what I'm doing, which works great. It would be cool if my custom frames matched up.

Maybe it would be good as an option in the plugin settings.

Electron seems to have a simple API for this:
https://stackoverflow.com/questions/59609852/override-prefers-color-scheme-in-electron

Thanks for this plugin, very handy and allows you to spend more time living in Obsidian by bringing things like calendars into the workflow.

**Comment by oyes77** [comment]
I have the same problem with Gcalendar, I'm on dark mode but it's on light mode, do I need to make a manual adjustmen?

**Comment by replete** [comment]
I made a CSS snippet for custom frames in [this repo](https://github.com/replete/obsidian-minimal-theme-css-snippets) that makes the frame dim until you hover over it. It's made for minimal theme but you could adapt if you want though I'm unable to do it for you
