### ISSUE TITLE
Google Drive links fail with Error 401 Unauthorized

### ISSUE THREAD

**Issue by oscarlosu** [Ellpeck/ObsidianCustomFrames#75]
I'm trying to embed a Google Sheet in an Obsidian note. I'd like to not have to make the sheet publicly accessible, but if I make it private, I get this Error 401 Unauthorized when displaying the note with the embed.
I'm using Obsidian 1.1.16.

**Comment by Ellpeck** [comment]
Did you log in to your Google account in Obsidian before opening the sheet? You might have to temporarily create a separate frame that links to the Google home page (or some other part of Google that makes it easy to log in) and log in once before you can check the sheet. You can find more info about this sort of issue at #40 as well!

**Comment by oscarlosu** [comment]
I'll try that, thanks!

**Comment by Ellpeck** [comment]
Hi! I'm closing this issue for now due to inactivity. If you're still experiencing it, please leave a comment so I can reopen it.
