### ISSUE TITLE
Obsidian hotkeys don't work while custom frame has focus

### ISSUE THREAD

**Issue by maggaou** [Ellpeck/ObsidianCustomFrames#78]
Possibly related to #59. Hotkeys like "Focus on last note" don't work if a website in the custom frame has focus. For example, in the custom frame, if the focus is in a text input box, I cannot use cmd + 1 which I have set to "focus on last note".  Other examples include "Create new note" and "Search: Search in all files". If the last user actions were in the top bar in the custom frame, then Obsidian hotkeys are not overridden. I tried other key combinations like control + option + j, **but it seems the website in the custom frame hijacks globally every possible Obsidian hotkey.**

**Comment by Ellpeck** [comment]
This is related to #49, and essentially has the same problems and potential fixes.
