### ISSUE TITLE
FR: Add backward and forward buttons

### ISSUE THREAD

**Issue by HEmile** [Ellpeck/ObsidianCustomFrames#8]
On sites like wikipedia, going back and forth all the time is really useful! A backward and forward button would help tremendously with this.
However... From an earlier plugin I was working on (Search on Internet) I recall that this is really hard/impossible to do with IFrames. Hopefully with your extension it's possible :)

**Comment by Ellpeck** [comment]
Custom Frames actually uses webviews instead of iframes on Desktop, and I'm pretty sure it's possible with those!
