### ISSUE TITLE
Просто

### ISSUE THREAD

**Issue by SergeySoloArtist** [Ellpeck/ObsidianCustomFrames#82]
А сейчас еще проще```
Пррооо
```

- [ ] `про `
- [ ] Пррооо`хорошо то как `

**Comment by Ellpeck** [comment]
Hi, please try to speak English only on this issue tracker, so that communication is easiest. Also, machine translation of what you said.. makes no sense, so I don't know what you're trying to say.

**Comment by Ellpeck** [comment]
Hi! I'm closing this issue for now due to inactivity. If you're still experiencing it, please leave a comment so I can reopen it.
