### ISSUE TITLE
Embed Flaticon.com, copy icon not working

### ISSUE THREAD

**Issue by sparky1** [Ellpeck/ObsidianCustomFrames#87]
Several days ago, I embed Flaticon.com to OB by CustomFrame plugin. 

Firstly , It works, I can copy and paste icon from flaticon in sidebar to Excalidraw in OB.

But, today, it not working.  I can't copy icon  anymore. every time I tried,  it failed.

however, If I copy icon on Chrome browser, it still works. I don't know what's happend.

I was wondering could you please offer me some tips to fix this issue ? Thanks a lot!

<img width="890" alt="ob-issue" src="https://github.com/Ellpeck/ObsidianCustomFrames/assets/5470508/a0f71bd7-2dff-4aae-9bee-7cc2bea6f81c">

**Comment by Andrea-28-03** [comment]
I have the same problem with [Chat gpt](https://chat.openai.com/) and [perplexity](https://www.perplexity.ai/) the copy button doesn't do anything:
![image](https://github.com/Ellpeck/ObsidianCustomFrames/assets/62112468/8b46559a-2d45-412e-80d9-caa20f143edf)
![image](https://github.com/Ellpeck/ObsidianCustomFrames/assets/62112468/97e75330-1c10-48eb-8785-6fffb5af2d7f)
![image](https://github.com/Ellpeck/ObsidianCustomFrames/assets/62112468/1efe6117-b7b0-48b3-9295-636f04cf0994)
(chat gpt let you see that you really clicked the button but after that you haven't copied anything, like perplexity) 
They could be related problems, but for me is not that much of a deal becaouse i can olways copy selecting the text and ctrl+c

**Comment by Ellpeck** [comment]
This also should have been fixed in Obsidian 1.3.7. Please let me know if it hasn't, though!
