### ISSUE TITLE
Google Calendar: Can't sign-in

### ISSUE THREAD

**Issue by BrightStar219** [Ellpeck/ObsidianCustomFrames#90]
hi, I've just installed the customframes plugin (v2.4.6) and added Todoist which works great, but when added Google Calendar I get the welcome screen, but can't click on any button (sign-in).
I believe that a similar issue is mentioned here (https://github.com/Ellpeck/ObsidianCustomFrames/issues/76) but the closure reason is that it's fixed in Obsidian v1.3.7 while the official version is 1.3.5 (installed at Windows 11)

Will appreciate help with this issue.

**Comment by Ellpeck** [comment]
To sign in, you might have to first create a frame that opens the regular Google site and then log in there before heading back to your Todoist frame.

#75 has indeed been resolved by Obsidian 1.3.7, which might currently still be an Insiders version. There's nothing I can do from my side to fix sites not opening in the browser until it is officially released.

**Comment by BrightStar219** [comment]
thanks for the quick response. I've managed to hack this out by changing the calendar URL to the one with the sign-in popup, where I've managed to log in. Afterward, I reverted to the original URL and it seems to be working fine.
Thanks for the support!
