### ISSUE TITLE
Cannot Sign in to google calendar

### ISSUE THREAD

**Issue by AtivJoshi** [Ellpeck/ObsidianCustomFrames#93]
In the default google calendar frame, pressing the sign-in button does not take me to the sign-in page. This is probably because the sign-in button tries to open a new tab. What is the solution to this?

**Comment by Ellpeck** [comment]
Duplicate of #40. Please create a temporary frame that goes directly to the login page to log in there. Then, you can delete the temporary frame and you'll be logged in to your permanent one.

**Comment by AtivJoshi** [comment]
Thanks.
