### ISSUE TITLE
Mobile: Google Keep - Error 403

### ISSUE THREAD

**Issue by MatthewIIZ** [Ellpeck/ObsidianCustomFrames#94]
Opening Google Keep preset in Obsidian mobile results in error 403.

Default custom frame settings applied to the Google Keep preset.
![Screenshot_20230726-153022](https://github.com/Ellpeck/ObsidianCustomFrames/assets/139926278/e0c76b68-9c91-46e3-84e3-c5fc74808367)

**Comment by Ellpeck** [comment]
Hi! Please check this section of the README for more info on this error: https://github.com/Ellpeck/ObsidianCustomFrames#-on-obsidian-mobile
